cuda: True
ngpu: 1
gpu_id: '0'
data_dir: ../Train     # Your dataset path
video_flist: './filelists/Video_Name_List.txt'
audio_flist: './filelists/Audio_Name_List.txt'
workers: 4
batchSize: 70
checkpoint_folder: ./checkpoints
init_model: './checkpoints/VA_METRIC_state_epoch35.pth'
topk: 5
