cuda: True
#cuda: False
ngpu: 1
gpu_id: '0'
data_dir: ../Train     # Your dataset path
video_flist: './filelists/test_Name_List.txt'
audio_flist: './filelists/test_Name_List.txt'
workers: 4
batchSize: 50
checkpoint_folder: ./checkpoints
init_model: './checkpoints/VA_LSTM_state_epoch260_model1.pth'
topk: 5
init_encoder: ''
init_decoder: ''
afeat_pca: 64
vfeat_pca: 512
